// -------------
// For more documentation visit http://easydev.org/#/documentation/template/java
// -------------

/*
 * DO NOT EDIT THIS FILE
 * PLEASE EDIT ./custom/AuthorCustomService.js
 * THIS FILE WILL BE OVERWRITTEN ON THE NEXT EASYDEV'S CODE GENERATION
 * 
 */

app.factory('AuthorService', ['$resource', '$rootScope', 'AuthorServiceCustom',
  function($resource, $rootScope, AuthorServiceCustom){
    return $resource( $rootScope.baseUrl + "/author/:_id", {_id:'@_id'}, $.extend({
    }, AuthorServiceCustom));
}]);