// -------------
// For more documentation visit http://easydev.org/#/documentation/template/java
// -------------

/*
 * DO NOT EDIT THIS FILE
 * PLEASE EDIT ./custom/BookCustomService.js
 * THIS FILE WILL BE OVERWRITTEN ON THE NEXT EASYDEV'S CODE GENERATION
 * 
 */

app.factory('BookService', ['$resource', '$rootScope', 'BookServiceCustom',
  function($resource, $rootScope, BookServiceCustom){
    return $resource( $rootScope.baseUrl + "/book/:_id", {_id:'@_id'}, $.extend({
        'findBy_author': { 
        	url: $rootScope.baseUrl + '/book/findBy_author/:key',
        	method: 'GET',
        	isArray: true,
        	params: {
        		key: '@key',
        		 
        	}
        },
        'strictLinkListOf_author': { 
        	url: $rootScope.baseUrl + '/book/_author/:key',
        	method: 'POST',
        	isArray: true,
        	params: {
        		key: '@key',
        		 
        	}
        },
    }, BookServiceCustom));
}]);